version: 2.1

executors:
  machine-executor:
    machine:
      image: ubuntu-2004:202104-01

jobs:
  build:
    executor: machine-executor
    steps:
      - checkout
      - run:
          name: Install Docker
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io
      - run:
          name: Docker Login
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Build Docker Image
          command: |
            docker build -t my-app:latest .
      - run:
          name: Test Docker Image
          command: |
            docker run -d -p 8080:8080 --name test-container my-app:latest
            sleep 10  # Wait for the container to start
            curl --retry 5 --retry-delay 5 --retry-connrefused -f http://127.0.0.1:8080 || exit 1
            docker stop test-container
            docker rm test-container

workflows:
  version: 2
  build-and-push:
    jobs:
      - build
