version: 2.1

# Import the Docker Orb
orbs:
  docker: circleci/docker@2.1.0  # Use the latest stable version

jobs:
  build-and-push:
    docker:
      - image: circleci/python:3.8  # This is the base image used for the job
    steps:
      - checkout  # Checkout your code
      - docker/login:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD  # Use environment variables for DockerHub credentials
      - docker/build:
          image: my-app  # Name of your Docker image
          tag: latest  # Tag your image as "latest"
      - docker/push:
          image: $DOCKERHUB_USERNAME/my-app  # Push the image to Docker Hub under your username

workflows:
  version: 2
  build-and-push:
    jobs:
      - build-and-push
