version: 2.1

jobs:
  build-and-run-docker:
    # Utilisation de l'exécuteur "machine" avec une image Ubuntu 22.04
    machine:
      image: ubuntu-2204:current

    steps:
      - checkout

      - run:
          name: Construire l'image Docker
          command: |
            sudo docker build -t my-app .

      - run:
          name: Vérifier l'image Docker
          command: |
            sudo docker images | grep my-app

      - run:
          name: Exécuter le conteneur Docker
          command: |
            sudo docker run -d -p 80:8080 --name my-app-container my-app

      - run:
          name: Tester le conteneur Docker
          command: |
            sleep 5  # Attendre que le conteneur soit prêt
            curl -X GET http://127.0.0.1/users || (echo "Le conteneur Docker n'a pas répondu comme prévu" && exit 1)

      - run:
          name: Nettoyer le conteneur Docker
          command: |
            sudo docker stop my-app-container
            sudo docker rm my-app-container

      - run:
          name: Connexion à Docker Hub
          command: |
            echo $DOCKERHUB_PASSWORD | sudo docker login -u $DOCKERHUB_LOGIN --password-stdin

      - run:
          name: Pousser l'image Docker vers DockerHub
          command: |
            sudo docker tag my-app $DOCKERHUB_USERNAME/my-app:latest
            sudo docker push $DOCKERHUB_USERNAME/my-app:latest

workflows:
  version: 2
  build-and-run:
    jobs:
      - build-and-run-docker
