version: 2.1

# Import the Docker Orb
orbs:
  docker: circleci/docker@2.8.1  # Use the latest stable version of the Docker Orb

jobs:
  build-and-push:
    docker:
      - image: circleci/python:3.8  # This is the Docker image you're using for the job, you can change it as needed
    steps:
      - checkout  # Checkout your repository code
      - setup_remote_docker:
          version: 20.10.7  # Specify the Docker version (if needed)
          docker_layer_caching: true  # Enable caching for Docker layers to speed up builds
      - docker/login:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD  # Use the stored environment variables for DockerHub login
      - docker/build:
          image: my-app  # The name of the Docker image you want to build
          tag: latest  # The tag for your Docker image
      - docker/push:
          image: $DOCKERHUB_USERNAME/my-app:latest  # Push the built Docker image to DockerHub

workflows:
  version: 2
  build-and-push:
    jobs:
      - build-and-push
