version: 2.1

executors:
  machine-executor:
    machine:
      image: ubuntu-2004:current

jobs:
  build:
    executor: machine-executor
    steps:
      - checkout
      - run:
          name: Install Docker Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            sudo apt-get update
      - run:
          name: Install Docker
          command: |
            sudo apt-get install -y containerd.io
            sudo apt-get install -y docker-ce docker-ce-cli
      - run:
          name: Build Docker Image
          command: |
            docker build -t my-app:latest .
      - run:
          name: Test Docker Image
          command: |
            docker run -d -p 8080:3000 --name test-container my-app:latest
            sleep 30
            curl --retry 5 --retry-delay 5 --retry-connrefused -f http://localhost:8080 || exit 1
            docker stop test-container
            docker rm test-container

workflows:
  version: 2
  build-and-push:
    jobs:
      - build
