name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Déclencher le workflow sur les pushs vers la branche "main"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Connexion à Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Étape 3 : Construire l'image Docker
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest .

      # Étape 4 : Tester l'image Docker
      - name: Test Docker container
        run: |
          docker run -d -p 8080:8080 --name my-app-container ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
          sleep 5  # Attendre que le conteneur démarre
          curl --retry 5 --retry-delay 5 --retry-connrefused -f http://127.0.0.1:8080 || exit 1
          docker stop my-app-container
          docker rm my-app-container

      # Étape 5 : Pousser l'image sur Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
